# Generated by Django 4.2.4 on 2023-09-04 01:24

import bbs.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='カテゴリ名')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='bbs/document/file/', verbose_name='ファイル')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='bbs/album/photo/', verbose_name='フォト')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日')),
                ('comment', models.CharField(max_length=2000, verbose_name='コメント')),
                ('name', models.CharField(default='匿名希望', max_length=20, verbose_name='名前')),
                ('age', models.IntegerField(default=20, verbose_name='年齢')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=2000, validators=[bbs.models.validate_bad_words], verbose_name='コメント')),
                ('dt', models.DateTimeField(auto_now=True, verbose_name='投稿日時')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.category', verbose_name='カテゴリ')),
            ],
        ),
    ]
