# Generated by Django 4.2.4 on 2023-08-28 23:16

import bbs.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=2000, validators=[bbs.models.validate_bad_words], verbose_name='コメント')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
            ],
        ),
    ]
