# Generated by Django 4.2.4 on 2023-08-23 01:17

import bbs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='upload/album/photo/', verbose_name='フォト')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload/document/file/', verbose_name='ファイル')),
            ],
        ),
        migrations.AlterField(
            model_name='topic',
            name='comment',
            field=models.CharField(max_length=2000, validators=[bbs.models.validate_bad_words], verbose_name='コメント'),
        ),
    ]
