# Generated by Django 4.2.4 on 2023-08-26 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_topic_dt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='dt',
        ),
    ]
