# Generated by Django 4.2.4 on 2023-08-26 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_sample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
